DROP VIEW IF EXISTS Tpch;
CREATE VIEW Tpch AS SELECT * FROM orders LIMIT 100;

SELECT *
FROM Tpch R
DECIDE x
SUCH THAT x IS INTEGER AND
    x BETWEEN 0 AND 1 AND
    SUM(o_totalprice*x) <= 454000 AND
    SUM(o_shippriority*x) >= 0 AND
    SUM(x) >= 1
MINIMIZE SUM(x);