DROP VIEW IF EXISTS Tpch;
CREATE VIEW Tpch AS SELECT *, l_extendedprice AS revenue FROM lineitem LIMIT 100;

SELECT *
FROM Tpch R
DECIDE x
SUCH THAT x IS INTEGER AND
    x BETWEEN 0 AND 1 AND
    SUM(revenue*x) >= 720000 AND
    SUM(x) >= 1
MINIMIZE SUM(x)