name: On Tag
on:
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string

jobs:
  twine_upload:
    uses: ./.github/workflows/TwineUpload.yml
    secrets: inherit
    with:
      override_git_describe: ${{ inputs.override_git_describe || github.ref_name }}
      twine_upload: 'true'

  staged_upload:
    uses: ./.github/workflows/StagedUpload.yml
    secrets: inherit
    with:
      target_git_describe: ${{ inputs.override_git_describe || github.ref_name }}
